name: logkeeper
description: Simple file logger that works out of the box with automatic timestamping and session management.
version: 1.1.0+2
repository: https://github.com/RaulCatalinas/LogKeeper


environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  path: ^1.9.0
  intl: ^0.20.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
